import streamlit as st
import os
from dotenv import load_dotenv
from ai_avatar import generate_image, instagram_upload, instagram_publish

# Load environment variables
load_dotenv()

st.set_page_config(page_title="AI Avatar Agent", page_icon="🤖")

st.title("🤖 AI Avatar Agent")
st.markdown("Generate AI avatars and post them to Instagram!")

# --- Session State ---
if "image_url" not in st.session_state:
    st.session_state.image_url = None
if "generated" not in st.session_state:
    st.session_state.generated = False

# --- Section 1: Generate Image ---
st.header("1. Generate Avatar")
image_prompt = st.text_area("Enter Image Prompt", value="anime style, male programmer standing with his AI waifu", height=100)

if st.button("Generate Image"):
    with st.spinner("Generating image with DALL-E 3..."):
        try:
            image_url = generate_image(image_prompt)
            st.session_state.image_url = image_url
            st.session_state.generated = True
            st.success("Image generated successfully!")
        except Exception as e:
            st.error(f"Error generating image: {e}")

if st.session_state.generated and st.session_state.image_url:
    st.image(st.session_state.image_url, caption="Generated Avatar", use_container_width=True)

    # --- Section 2: Post to Instagram ---
    st.divider()
    st.header("2. Post to Instagram")
    
    caption = st.text_area("Enter Caption", value="Generated by AI Avatar Automation #AI #Coding", height=100)
    
    if st.button("Post to Instagram"):
        with st.spinner("Uploading and Publishing to Instagram..."):
            try:
                # 1. Upload to Container
                container_id = instagram_upload(st.session_state.image_url, caption)
                st.info(f"Uploaded to container: {container_id}")
                
                # 2. Publish
                result = instagram_publish(container_id)
                st.success(f"Published successfully! ID: {result.get('id')}")
                st.balloons()
            except Exception as e:
                st.error(f"Error posting to Instagram: {e}")
